### ISSUE TITLE
"python3 litmustestrunner.py -g" Fails due to generate_thread_header definition

### ISSUE THREAD

**Issue by perlfu** [reeselevine/litmus-generator#4]
Looks like Vulkan generator code is not up to date?

```
$ python3 litmustestrunner.py message-passing -g
Generating message-passing litmus test for backend vulkan
Traceback (most recent call last):
  File "litmustestrunner.py", line 147, in <module>
    main()
  File "litmustestrunner.py", line 121, in main
    generate(test_config, parameter_config, backend)
  File "litmustestrunner.py", line 28, in generate
    litmus_test.generate()
  File "/amd/_git/litmus-generator/litmusgenerator.py", line 110, in generate
    thread_statements = self.generate_thread_header(thread.workgroup, thread.local_id, thread.has_barrier)
TypeError: generate_thread_header() takes 1 positional argument but 4 were given
```

**Comment by reeselevine** [comment]
@perlfu yeah sorry about that! We've been focused on webgpu stuff recently, but I will eventually get back to this and get it working for Vulkan generation as well. I also need to add some documentation on how to run the shaders once they are generated.

**Comment by perlfu** [comment]
No problem!
I filed this before I heard you'd been focusing on WebGPU recently.
